PRODUCT = snd_paula.dll
INSTLOCATION =
SRC = snd_amiga.c
OBJ = snd_amiga.o

include /amiga/config.mk

snd_amiga.o: snd_amiga.c snd_interrupt.h

snd_interrupt.h: snd_interrupt.s
	asm snd_interrupt.s
	objcopy -I amiga -O binary snd_interrupt.o
	/genheader snd_interrupt.o snd_interrupt.h intcode
